config/routes.rb
AdvancedAr::Application.routes.draw do
  root to: 'todo_lists#index'
  resources :todo_lists do
    resources :todo_items
  end

  resources :accounts, only: [:show, :edit, :update]

  resources :sessions, only: [:new, :create, :destroy]
  get '/login' => 'sessions#new', as: 'login'
  delete '/logout' => 'sessions#destroy', as: 'logout'
end

app/models/todo_item.rb
class TodoItem < ActiveRecord::Base
  belongs_to :todo_list
  has_and_belongs_to_many :tags
  attr_accessible :description, :due_date, :task_title, :done
  default_scope order('due_date ASC')

  validates :task_title, presence: true
  validates :due_date, presence: true
  validate :not_due_after_list

  def not_due_after_list
    if todo_list
      errors.add(:due_date, 'The due date must be the same as or earlier than the todo list due date') if self.due_date > todo_list.list_due_date
    end
  end

end

app/controllers/todo_items_controller.rb
class TodoItemsController < ApplicationController
  before_filter :set_todo_list
  before_filter :set_todo_item, only: [:show, :edit, :update, :destroy]

  # GET todo_lists/1/todo_items/1
  # GET todo_lists/1/todo_items/1.json
  def show
    respond_to do |format|
      format.json { render json: @todo_item }
      format.js #show.js.coffee
    end
  end

  # GET todo_lists/1/todo_items/new
  # GET todo_lists/1/todo_items/new.json
  def new
    @todo_item = TodoItem.new

    respond_to do |format|
      format.json { render json: @todo_item }
      format.js #new.js.coffee
    end
  end

  # GET todo_lists/1/todo_items/1/edit
  def edit
    respond_to do |format|
      format.js # edit.js.coffee
    end
  end

  # POST todo_lists/1/todo_items
  # POST todo_lists/1/todo_items.json
  def create
    @todo_item = TodoItem.new(params[:todo_item])
    @todo_list.todo_items << @todo_item

    respond_to do |format|
      if @todo_item.save
        format.json { render json: @todo_item, status: :created, location: @todo_item }
        format.js #create.js.coffee
      else
        format.json { render json: @todo_item.errors, status: :unprocessable_entity }
        format.js { render action: "new" }
      end
    end
  end

  # PUT todo_lists/1/todo_items/1
  # PUT todo_lists/1/todo_items/1.json
  def update
    respond_to do |format|
      if @todo_item.update_attributes(params[:todo_item])
        format.json { head :no_content }
        format.js #update.js.coffee
      else
        format.json { render json: @todo_item.errors, status: :unprocessable_entity }
        format.js { render action: "edit" }
      end
    end
  end

  # DELETE todo_lists/1/todo_items/1
  # DELETE todo_lists/1/todo_items/1.json
  def destroy
    @todo_item.destroy

    respond_to do |format|
      format.html { redirect_to [@todo_list], notice: 'Todo item deleted successfully.' }
      format.json { head :no_content }
    end
  end

  private
    def set_todo_list
      @todo_list = TodoList.find params[:todo_list_id]
    end

    def set_todo_item
      @todo_item = TodoItem.find(params[:id])
    end

end

app/helpers/todo_items_helper.rb
module TodoItemsHelper
end

app/views/todo_items/_form.html.erb
<%= form_for([@todo_list, @todo_item], remote: true) do |f| %>
  <% if @todo_item.errors.any? %>
    <div class='alert alert-danger' id="error_explanation">
      <h3><%= pluralize(@todo_item.errors.count, "error") %> prohibited this todo_item from being saved:</h3>

      <ul>
      <% @todo_item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <div class="field form-group">
      <%= f.label :task_title, 'Task' %>
      <%= f.text_field :task_title, class: 'form-control', placeholder: 'Your new list item' %>
      <%= f.label :description, 'Description' %>
      <%= f.text_area :description, rows: 5, class: 'form-control', placeholder: 'Task description' %>
    </div>
    <div class="field form-group form-inline">
      <%= f.label :due_date, 'Due date' %><br>
      <%= f.text_field :due_date, class: 'form-control date-picker' %>
    </div>
    <% if params[:id] %>
      <div class='field checkbox'>
        <label for='done'>
          <%= f.check_box :done %> Mark this task completed
        </label>
      </div>
    <% end %>
    <%= f.submit class: 'btn btn-info' %>
  </div>
<% end %>

app/views/todo_items/_todo_item.html.erb
<%= content_tag :li, class: 'list-group-item' do %>
  <div>
    <h3>
      <%= link_to todo_item.task_title, [@todo_list, todo_item], remote: true %>
      <%= link_to '#', remote: true, class: 'mark-done', data: {done: todo_item.done?, list: @todo_list.id, item: todo_item.id}  do %>
        <% common_classes = 'item-done-badge pull-right glyphicon' %>
        <% if todo_item.done? %>
          <%= content_tag :span, '', class: "#{common_classes} glyphicon-ok-sign done" %>
        <% else %>
          <%= content_tag :span, '', class: "#{common_classes} glyphicon-exclamation-sign pending" %>
        <% end %>
      <% end %>
    </h3>
    <%= content_tag :div, '', id: "details-container-#{@todo_list.id}-#{todo_item.id}" %>
    <hr/>
    Due on <%= time_tag todo_item.due_date %>
    <div class='pull-right'>
      <%= link_to 'Edit', edit_todo_list_todo_item_path(@todo_list, todo_item), remote: true %> |
      <%= link_to 'Destroy', [@todo_list, todo_item], method: :delete, data: {confirm: "Delete item '#{todo_item.task_title}' permenantly?"} %>
    </div>
  </div>
  <%= content_tag :div, '', id: "form-container-#{@todo_list.id}-#{todo_item.id}" %>
<% end %>

app/views/todo_items/description.html.erb
<div class='row'>
  <div class='col-md-1 col-xs-1'>
    <%= content_tag :a, href: '', id: "close-desc-#{@todo_list.id}-#{@todo_item.id}" do %>
      <span class='glyphicon glyphicon-menu-up'></span>
    <% end %>
  </div>
  <div class='col-md-11 col-xs-11'>
    <%= @todo_item.description %>
  </div>
  <hr/>
</div>

app/views/todo_items/edit.html.erb
<div class='page-header'>
  <h3>
    Edit todo item
    <small>'<%= @todo_item.task_title %>'</small>
    <%= content_tag :button, class: 'btn btn-warning pull-right', id: "cancel-btn-#{@todo_list.id}-#{@todo_item.id}" do %>
      <span class='glyphicon glyphicon-remove'></span>
    <% end %>
  </h3>
</div>

<%= render 'form' %>

app/views/todo_items/new.html.erb
<div class='page-header'>
  <h3>
    New todo item
    <small>for '<%= @todo_list.list_name %>'</small>
    <button class='btn btn-warning pull-right' id='cancel-btn'><span class='glyphicon glyphicon-remove'></span></button>
  </h3>
</div>

<%= render 'form' %>