config/routes.rb
AdvancedAr::Application.routes.draw do
  root to: 'todo_lists#index'
  resources :todo_lists do
    resources :todo_items
  end

  resources :accounts, only: [:show, :edit, :update]

  resources :sessions, only: [:new, :create, :destroy]
  get '/login' => 'sessions#new', as: 'login'
  delete '/logout' => 'sessions#destroy', as: 'logout'
end

app/models/todo_list.rb
class TodoList < ActiveRecord::Base
  belongs_to :user
  has_many :todo_items, dependent: :delete_all
  attr_accessible :list_due_date, :list_name
  default_scope order('list_due_date ASC')

  validates :list_name, presence: true
  validates :list_due_date, presence: true
end

app/controllers/todo_lists_controller.rb
class TodoListsController < ApplicationController
  before_filter :set_todo_list, only: [:show, :edit, :update, :destroy]

  # GET /todo_lists
  # GET /todo_lists.json
  def index
    @todo_lists = current_user.todo_lists.paginate(page: params[:page], per_page: 6)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @todo_lists }
    end
  end

  # GET /todo_lists/1
  # GET /todo_lists/1.json
  def show
    @items = @todo_list.todo_items.paginate(page: params[:page], per_page: 6)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @todo_list }
    end
  end

  # GET /todo_lists/new
  # GET /todo_lists/new.json
  def new
    @todo_list = current_user.todo_lists.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @todo_list }
      format.js # new.js.coffee
    end
  end

  # GET /todo_lists/1/edit
  def edit
    respond_to do |format|
      format.html # edit.html.erb
      format.js #edit.js.coffee
    end
  end

  # POST /todo_lists
  # POST /todo_lists.json
  def create
    @todo_list = current_user.todo_lists.new(params[:todo_list])

    respond_to do |format|
      if @todo_list.save
        format.html { redirect_to @todo_list, notice: 'Todo list was successfully created.' }
        format.json { render json: @todo_list, status: :created, location: @todo_list }
        format.js # create.js.coffee
      else
        format.html { render action: "new" }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /todo_lists/1
  # PUT /todo_lists/1.json
  def update
    respond_to do |format|
      if @todo_list.update_attributes(params[:todo_list])
        format.html { redirect_to @todo_list, notice: 'Todo list was successfully updated.' }
        format.json { head :no_content }
        format.js # update.js.coffee
      else
        format.html { render action: "edit" }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todo_lists/1
  # DELETE /todo_lists/1.json
  def destroy
    @todo_list.destroy

    respond_to do |format|
      format.html { redirect_to todo_lists_url }
      format.json { head :no_content }
    end
  end

  private
    def set_todo_list
      @todo_list = current_user.todo_lists.find params[:id]
    end

end

app/helpers/todo_lists_helper.rb
module TodoListsHelper
end

app/views/todo_lists/_form.html.erb
<%= form_for(@todo_list, remote: true) do |f| %>
  <% if @todo_list.errors.any? %>
    <div class='alert alert-danger' id="error_explanation">
      <h3><%= pluralize(@todo_list.errors.count, "error") %> prohibited this todo_list from being saved:</h3>

      <ul>
      <% @todo_list.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <div class="field form-group">
      <%= f.label :list_name, 'Name' %>
      <%= f.text_field :list_name, class: 'form-control', placeholder: 'Your new list' %>
    </div>
    <div class="field form-group form-inline">
      <%= f.label :list_due_date, 'Due date' %><br>
      <%= f.text_field :list_due_date, class: 'form-control date-picker' %>
    </div>
    <%= f.submit class: 'btn btn-info' %>
  </div>
<% end %>

app/views/todo_lists/_todo_list.html.erb
<% completed = true %>
<% todo_list.todo_items.each {|item| completed = false unless item.done?} %>
<li class='list-group-item'>
  <div>
    <h3>
      <%= link_to todo_list.list_name, todo_list %>
      <span class='badge'><%= pluralize(todo_list.todo_items.length, 'item') if todo_list.todo_items.length > 0 %></span>
      <% if completed %>
        <span class='pull-right glyphicon glyphicon-ok-sign done'></span>
      <% else %>
        <span class='pull-right glyphicon glyphicon-exclamation-sign pending'></span>
      <% end %>
    </h3>
    <hr/>
    Due on <%= time_tag todo_list.list_due_date %>
    <div class='pull-right'>
      <%= link_to 'Edit', edit_todo_list_path(todo_list), remote: true %> |
      <%= link_to 'Destroy', todo_list, method: :delete, data: {confirm: "Delete list '#{todo_list.list_name}' permenantly?"} %>
    </div>
  </div>
  <%= content_tag :div, '', id: "form-container-#{todo_list.id}" %>
</li>

app/views/todo_lists/edit.html.erb
<div class='page-header'>
  <h1>Edit Todo List '<%= @todo_list.list_name %>'</h1>
</div>

<div class='row'>
  <div class='col-md-2'>
    <ul class='nav nav-pills nav-stacked'>
      <li><%= link_to 'Show', @todo_list %></li>
      <li><%= link_to 'Back', todo_list_path(@todo_list) %></li>
    </ul>
  </div>
  <div class='col-md-10'>
    <%= form_for(@todo_list) do |f| %>
      <% if @todo_list.errors.any? %>
        <div class='alert alert-danger' id="error_explanation">
          <h3><%= pluralize(@todo_list.errors.count, "error") %> prohibited this todo_list from being saved:</h3>

          <ul>
          <% @todo_list.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="actions">
        <div class="field form-group">
          <%= f.label :list_name, 'Name' %>
          <%= f.text_field :list_name, class: 'form-control', placeholder: 'Your new list' %>
        </div>
        <div class="field form-group form-inline">
          <%= f.label :list_due_date, 'Due date' %><br>
          <%= f.text_field :list_due_date, class: 'form-control date-picker' %>
        </div>
        <%= f.submit class: 'btn btn-info' %>
      </div>
    <% end %>
  </div>
</div>

app/views/todo_lists/index.html.erb
<div class='page-header'>
  <h1>Todo Lists</h1>
</div>

<div class='row'>
  <div class='col-md-2'></div>
  <div class='col-md-10 col-sm-12'>
    <ul class='list-group' id='main-list'>
      <li class='list-group-item alt'>
        <h3 class='compact'>
          <%= link_to 'Add a new list', new_todo_list_path, remote: true, class: 'no-link-color' %>
          <%= link_to new_todo_list_path, remote: true, class: 'no-link-color' do %>
            <% content_tag(:span, '', class: 'pull-right glyphicon glyphicon-plus-sign') %>
          <% end %>
        </h3>
        <div class='hidden' id='form-container'></div>
      </li>
      <%= render partial: 'todo_list', collection: @todo_lists %>
    </ul>
  </div>
  <div class='col-md-12 text-center'>
    <%= will_paginate @todo_lists, renderer: BootstrapPagination::Rails %>
  </div>
</div>

app/views/todo_lists/inline_edit.html.erb
<div class='page-header'>
  <h3>
    Edit todo list
    <small>'<%= @todo_list.list_name %>'</small>
    <%= content_tag :button, class: 'btn btn-warning pull-right', id: "cancel-btn-#{@todo_list.id}" do %>
      <span class='glyphicon glyphicon-remove'></span>
    <% end %>
  </h3>
</div>

<%= render 'form' %>

app/views/todo_lists/new.html.erb
<div class='page-header'>
  <h3>
    New Todo List
    <button class='btn btn-warning pull-right' id='cancel-btn'><span class='glyphicon glyphicon-remove'></span></button>
  </h3>
</div>

<%= render 'form' %>

app/views/todo_lists/show.html.erb
<div class='page-header'>
  <h1>
    <%= @todo_list.list_name %>
    <small>Due on <%= time_tag @todo_list.list_due_date %></small>
  </h1>
</div>

<div class='row'>
  <div class='col-md-2'>
    <ul class='nav nav-pills nav-stacked'>
      <li><%= link_to 'Edit', edit_todo_list_path(@todo_list) %></li>
      <li><%= link_to 'Back', todo_lists_path %></li>
    </ul>
  </div>
  <div class='col-md-10 col-sm-12' id='main-list'>
    <ul class='list-group'>
      <li class='list-group-item alt'>
        <h3 class='compact'>
          <%= link_to 'Add a new list item', new_todo_list_todo_item_path(@todo_list), remote: true, class: 'no-link-color' %>
          <%= link_to new_todo_list_todo_item_path(@todo_list), remote: true, class: 'no-link-color' do %>
            <% content_tag(:span, '', class: 'pull-right glyphicon glyphicon-plus-sign') %>
          <% end %>
        </h3>
        <div class='hidden' id='form-container'></div>
      </li>
      <%= render partial: 'todo_items/todo_item', collection: @items %>
    </ul>
  </div>
  <div class='col-md-12 text-center'>
    <%= will_paginate @items, renderer: BootstrapPagination::Rails %>
  </div>
</div>